"""
Interactive environment configuration script
Helps set up .env file with all necessary environment variables
"""

import os
import sys
from pathlib import Path

def get_input(prompt, default=None, secret=False):
    """Get user input with optional default value"""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    if secret:
        import getpass
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)
    
    return value.strip() if value.strip() else default

def configure_database():
    """Configure database settings"""
    print("\n" + "="*60)
    print("Database Configuration")
    print("="*60)
    print("\nChoose database type:")
    print("1. PostgreSQL (Production)")
    print("2. SQLite (Development)")
    
    choice = input("\nEnter choice [1]: ").strip() or "1"
    
    if choice == "1":
        print("\nPostgreSQL Configuration")
        print("-" * 60)
        
        use_full_url = get_input(
            "Use full connection string? (y/n)",
            "n"
        ).lower() == "y"
        
        if use_full_url:
            db_url = get_input(
                "Enter PostgreSQL connection string",
                "postgresql+psycopg2://user:password@localhost:5432/impact_investing"
            )
            return {"DATABASE_URL": db_url}
        else:
            db_user = get_input("Database user", "postgres")
            db_password = get_input("Database password", secret=True)
            db_host = get_input("Database host", "localhost")
            db_port = get_input("Database port", "5432")
            db_name = get_input("Database name", "impact_investing")
            
            return {
                "DB_USER": db_user,
                "DB_PASSWORD": db_password,
                "DB_HOST": db_host,
                "DB_PORT": db_port,
                "DB_NAME": db_name
            }
    else:
        print("\nUsing SQLite for development")
        db_path = get_input("Database file path", "./impact_investing.db")
        return {"DATABASE_URL": f"sqlite:///{db_path}"}

def configure_application():
    """Configure application settings"""
    print("\n" + "="*60)
    print("Application Configuration")
    print("="*60)
    
    env = get_input("Environment (development/staging/production)", "development")
    debug = get_input("Debug mode (true/false)", "true").lower() == "true"
    api_host = get_input("API host", "0.0.0.0")
    api_port = get_input("API port", "8000")
    api_reload = get_input("Auto-reload on code changes (true/false)", "true").lower() == "true"
    
    return {
        "ENVIRONMENT": env,
        "DEBUG": str(debug).lower(),
        "API_HOST": api_host,
        "API_PORT": api_port,
        "API_RELOAD": str(api_reload).lower()
    }

def configure_advanced():
    """Configure advanced settings"""
    print("\n" + "="*60)
    print("Advanced Configuration")
    print("="*60)
    
    sql_echo = get_input("Enable SQL query logging (true/false)", "false").lower() == "true"
    log_level = get_input("Log level (DEBUG/INFO/WARNING/ERROR)", "INFO")
    
    config = {
        "SQL_ECHO": str(sql_echo).lower(),
        "LOG_LEVEL": log_level
    }
    
    return config

def write_env_file(config, env_file_path):
    """Write configuration to .env file"""
    env_file = Path(env_file_path)
    
    # Read example file if it exists
    example_file = env_file.parent / ".env.example"
    comments = []
    if example_file.exists():
        with open(example_file, 'r') as f:
            lines = f.readlines()
            # Extract relevant comments
            for line in lines:
                if line.strip().startswith('#') and not line.strip().startswith('# '):
                    comments.append(line.rstrip())
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# ============================================\n")
        f.write("# Impact Investing Research Tool - Environment Configuration\n")
        f.write("# ============================================\n")
        f.write("# Generated by configure_env.py\n")
        f.write("# DO NOT commit this file to version control\n")
        f.write("# ============================================\n\n")
        
        # Write database configuration
        f.write("# Database Configuration\n")
        f.write("# ============================================\n")
        for key, value in config.items():
            if key.startswith("DB_") or key == "DATABASE_URL":
                f.write(f"{key}={value}\n")
        
        f.write("\n# Application Configuration\n")
        f.write("# ============================================\n")
        for key, value in config.items():
            if key not in ["DATABASE_URL", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT", "DB_NAME", "SQL_ECHO", "LOG_LEVEL"]:
                f.write(f"{key}={value}\n")
        
        f.write("\n# Advanced Settings\n")
        f.write("# ============================================\n")
        if "SQL_ECHO" in config:
            f.write(f"SQL_ECHO={config['SQL_ECHO']}\n")
        if "LOG_LEVEL" in config:
            f.write(f"LOG_LEVEL={config['LOG_LEVEL']}\n")

def main():
    """Main configuration function"""
    print("="*60)
    print("Impact Investing Research Tool - Environment Configuration")
    print("="*60)
    print("\nThis script will help you configure your .env file.")
    print("You can skip any section by pressing Enter to use defaults.\n")
    
    # Get script directory
    script_dir = Path(__file__).parent
    env_file = script_dir / ".env"
    
    # Check if .env already exists
    if env_file.exists():
        overwrite = input(f"\n.env file already exists at {env_file}. Overwrite? (y/n) [n]: ").strip().lower()
        if overwrite != "y":
            print("Configuration cancelled.")
            return
    
    # Collect configuration
    config = {}
    
    # Database configuration
    config.update(configure_database())
    
    # Application configuration
    config.update(configure_application())
    
    # Advanced configuration
    advanced = input("\nConfigure advanced settings? (y/n) [n]: ").strip().lower()
    if advanced == "y":
        config.update(configure_advanced())
    else:
        # Set defaults
        config.update({
            "SQL_ECHO": "false",
            "LOG_LEVEL": "INFO"
        })
    
    # Write .env file
    write_env_file(config, env_file)
    
    print("\n" + "="*60)
    print("Configuration Complete!")
    print("="*60)
    print(f"\n✓ Environment file created at: {env_file}")
    print("\nNext steps:")
    print("1. Review the .env file and adjust values if needed")
    print("2. Run: python init_db.py (to initialize database)")
    print("3. Run: python -m uvicorn main:app --reload (to start server)")
    print("\n⚠️  Remember: .env file contains sensitive information.")
    print("   Never commit it to version control!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
        sys.exit(0)

